### ISSUE TITLE
Error running every script:

### ISSUE THREAD

**Issue by ghirardinicola** [hero-page/hero-ml#5]
> hero run app_proposal.heroml
/usr/local/lib/node_modules/heroml/dist/cli.js:22
const node_fetch_1 = __importDefault(require("node-fetch"));
                                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/node-fetch/src/index.js from /usr/local/lib/node_modules/heroml/dist/cli.js not supported.
Instead change the require of index.js in /usr/local/lib/node_modules/heroml/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/heroml/dist/cli.js:22:38) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.2.0

**Comment by ghirardinicola** [comment]
Solved using: npm install -g node-fetch@2

**Comment by kingmeers** [comment]
Hi @ghirardinicola glad to see it works with the fetch update! Going to close this :)
